/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GameCfgData
 * 
 * 访问性设计：
 * - _cfgDatas: private，使用者不可见
 * - Deserialize/Serialize: public（初始化时需要调用Deserialize）
 * - GetContainer<T>(): public，使用者通过此方法获取配置容器
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
    [Serializable]
    public partial class GameCfgData
    {
        private Dictionary<Type, ICfgContainer> _cfgDatas;

        public void Deserialize(BinaryReader reader)
        {
            _cfgDatas = new Dictionary<Type, ICfgContainer>();

            var _LanguageCfgContainer = new LanguageCfgContainer();
            _LanguageCfgContainer.Deserialize(reader);
            _cfgDatas.Add(typeof(LanguageCfg), _LanguageCfgContainer);

            var _ItemCfgContainer = new ItemCfgContainer();
            _ItemCfgContainer.Deserialize(reader);
            _cfgDatas.Add(typeof(ItemCfg), _ItemCfgContainer);
        }

        public void Serialize(BinaryWriter writer)
        {
            foreach (var item in _cfgDatas.Values)
            {
                item.Serialize(writer);
            }
        }

        /// <summary>
        /// 获取指定类型的配置容器（唯一的公开查询入口）
        /// </summary>
        public CfgContainerBase<T> GetContainer<T>() where T : class, ICfg
        {
            if (_cfgDatas.TryGetValue(typeof(T), out var container))
                return container as CfgContainerBase<T>;
            return null;
        }
    }
}
