/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * 
 * 基础接口定义
 * - ICfg: 公开接口，用于泛型约束
 * - IBinarySerialize: internal，使用者不可见
 * - ICfgContainer: internal，使用者不可见
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
    /// <summary>
    /// 配置项标记接口（公开，用于泛型约束）
    /// </summary>
    public interface ICfg
    {
    }

    /// <summary>
    /// 二进制序列化接口（internal，使用者不可见）
    /// </summary>
    internal interface IBinarySerialize
    {
        void Serialize(BinaryWriter writer);
        void Deserialize(BinaryReader reader);
    }

    /// <summary>
    /// 配置容器标记接口（internal，使用者不可见）
    /// </summary>
    internal interface ICfgContainer : IBinarySerialize
    {
    }
}
