/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ItemCfg
 * 
 * ============================================================
 * 这是一个示例文件，展示工具根据Excel自动生成的配置类结构
 * 
 * 示例1：int主键的Excel表格(item.xlsx)
 * ┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────────┬─────────────────┐
 * │ 第1行    │ id       │ name     │ price    │ stackable│ tags         │ attrs           │  ← 字段名
 * │ 第2行    │ 道具ID   │ 道具名称 │ 售价     │ 可否堆叠 │ 标签列表     │ 属性字典        │  ← 注释(跳过)
 * │ 第3行    │ int      │ string   │ int      │ bool     │ string[]     │ <string,int>    │  ← 字段类型
 * │ 第4行    │ (保留行) │          │          │          │              │                 │  ← 保留(跳过)
 * │ 第5行    │ 1001     │ 铁剑     │ 100      │ 0        │ weapon,melee │ atk:50,crit:10  │  ← 数据开始
 * │ 第6行    │ 1002     │ 生命药水 │ 50       │ 1        │ potion       │ hp:200          │
 * │ 第7行    │ 1003     │ 金币     │ 1        │ 1        │              │                 │  ← 空值=空数组/空字典
 * └──────────┴──────────┴──────────┴──────────┴──────────┴──────────────┴─────────────────┘
 * → 主键为 int 类型，容器使用 IntKeyMap
 *   Find(1001) 直接查字典，零GC分配
 *   支持的数组类型: int[], string[], bool[]（逗号分隔，空值为空数组）
 *   支持的字典类型: <int,int>, <int,string>, <string,int>等（冒号分隔键值，逗号分隔项）
 * 
 * 示例2：string主键的Excel表格(skill.xlsx)
 * ┌──────────┬──────────┬──────────┐
 * │ 第1行    │ id       │ name     │
 * │ 第2行    │ 技能ID   │ 技能名称 │
 * │ 第3行    │ string   │ string   │
 * │ 第4行    │ (保留行) │          │
 * │ 第5行    │ atk_001  │ 普通攻击 │
 * └──────────┴──────────┴──────────┘
 * → 主键为 string 类型，容器使用 StrKeyMap
 *   Find("atk_001") 直接查字典，零GC分配
 * 
 * 示例3：没有Id列的Excel表格(tips.xlsx)
 * ┌──────────┬──────────┐
 * │ 第1行    │ content  │  ← 没有id列
 * │ 第2行    │ 提示内容 │
 * │ 第3行    │ string   │
 * │ 第4行    │ (保留行) │
 * │ 第5行    │ 欢迎来到 │
 * │ 第6行    │ 按ESC退出│
 * └──────────┴──────────┘
 * → 工具自动生成 string 类型的 Id，值为索引("0","1","2"...)
 *   容器使用 StrKeyMap
 * ============================================================
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
    /// <summary>
    /// 道具配置数据类（int主键示例）
    /// </summary>
    [Serializable]
    public partial class ItemCfg : ICfg
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
        public int Price { get; private set; }
        public bool Stackable { get; private set; }
        public string[] Tags { get; private set; }
        public Dictionary<string, int> Attrs { get; private set; }

        internal void Deserialize(BinaryReader reader)
        {
            Id = reader.ReadInt32();
            Name = reader.ReadString();
            Price = reader.ReadInt32();
            Stackable = reader.ReadBoolean();
            Tags = new string[reader.ReadInt32()];
            for (int _i = 0; _i < Tags.Length; _i++) Tags[_i] = reader.ReadString();
            Attrs = new Dictionary<string, int>();
            int _Attrs_count = reader.ReadInt32();
            for (int _i = 0; _i < _Attrs_count; _i++) Attrs[reader.ReadString()] = reader.ReadInt32();
        }

        internal void Serialize(BinaryWriter writer)
        {
            writer.Write(Id);
            writer.Write(Name);
            writer.Write(Price);
            writer.Write(Stackable);
            writer.Write(Tags.Length);
            for (int _i = 0; _i < Tags.Length; _i++) writer.Write(Tags[_i]);
            writer.Write(Attrs.Count);
            foreach (var _kv in Attrs) { writer.Write(_kv.Key); writer.Write(_kv.Value); }
        }
    }

    /// <summary>
    /// 道具配置容器类（int主键 → KeyType = Int，使用IntKeyMap）
    /// 
    /// 使用示例：
    ///   var container = gameCfgData.GetContainer&lt;ItemCfg&gt;();
    ///   var sword = container.Find(1001);
    ///   Debug.Log(sword.Name);                    // "铁剑"
    ///   Debug.Log(sword.Tags[0]);                 // "weapon"
    ///   Debug.Log(sword.Attrs["atk"]);            // 50
    ///   Debug.Log(sword.Attrs["crit"]);           // 10
    /// </summary>
    [Serializable]
    public partial class ItemCfgContainer : CfgContainerBase<ItemCfg>
    {
        internal override void Deserialize(BinaryReader reader)
        {
            int count = reader.ReadInt32();
            InitIntKey(count);
            for (int i = 0; i < count; i++)
            {
                var item = new ItemCfg();
                item.Deserialize(reader);
                AddInt(item.Id, item);
            }
        }

        internal override void Serialize(BinaryWriter writer)
        {
            writer.Write(GetCount());
            foreach (var item in GetValues())
            {
                item.Serialize(writer);
            }
        }
    }
}
