/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * ItemCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	public partial class ItemCfg : ICfg
	{
		public int Id { get; private set; }
		public string Name { get; private set; }
		public int Price { get; private set; }
		public bool Stackable { get; private set; }
		public string[] Tags { get; private set; }
		public Dictionary<string, int> Attrs { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadInt32();
			Name = reader.ReadString();
			Price = reader.ReadInt32();
			Stackable = reader.ReadBoolean();
			Tags = new string[reader.ReadInt32()];
			for (int _i = 0; _i < Tags.Length; _i++) Tags[_i] = reader.ReadString();
			Attrs = new Dictionary<string, int>();
			int _Attrs_count = reader.ReadInt32();
			for (int _i = 0; _i < _Attrs_count; _i++) Attrs[reader.ReadString()] = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Price);
			writer.Write(Stackable);
			writer.Write(Tags.Length);
			for (int _i = 0; _i < Tags.Length; _i++) writer.Write(Tags[_i]);
			writer.Write(Attrs.Count);
			foreach (var _kv in Attrs) { writer.Write(_kv.Key); writer.Write(_kv.Value); }
		}
	}

	public partial class ItemCfgContainer : CfgContainerBase<ItemCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitIntKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new ItemCfg();
				item.Deserialize(reader);
				AddInt(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
