/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * SkillCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	public partial class SkillCfg : ICfg
	{
		public string Id { get; private set; }
		public string Name { get; private set; }
		public int Damage { get; private set; }
		public int[] Levels { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadString();
			Name = reader.ReadString();
			Damage = reader.ReadInt32();
			Levels = new int[reader.ReadInt32()];
			for (int _i = 0; _i < Levels.Length; _i++) Levels[_i] = reader.ReadInt32();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Name);
			writer.Write(Damage);
			writer.Write(Levels.Length);
			for (int _i = 0; _i < Levels.Length; _i++) writer.Write(Levels[_i]);
		}
	}

	public partial class SkillCfgContainer : CfgContainerBase<SkillCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitStrKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new SkillCfg();
				item.Deserialize(reader);
				AddStr(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
