/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * TipsCfg
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	public partial class TipsCfg : ICfg
	{
		public string Id { get; private set; }
		public string Content { get; private set; }

		internal void Deserialize(BinaryReader reader)
		{
			Id = reader.ReadString();
			Content = reader.ReadString();
		}

		internal void Serialize(BinaryWriter writer)
		{
			writer.Write(Id);
			writer.Write(Content);
		}
	}

	public partial class TipsCfgContainer : CfgContainerBase<TipsCfg>
	{
		protected override void Deserialize(BinaryReader reader)
		{
			int count = reader.ReadInt32();
			InitStrKey(count);
			for (int i = 0; i < count; i++)
			{
				var item = new TipsCfg();
				item.Deserialize(reader);
				AddStr(item.Id, item);
			}
		}

		protected override void Serialize(BinaryWriter writer)
		{
			writer.Write(GetCount());
			foreach (var item in GetValues()) item.Serialize(writer);
		}
	}
}
