using System.Text;

namespace ExcelTool
{
    /// <summary>
    /// C#代码生成器
    /// </summary>
    internal static class CodeGenerator
    {
        /// <summary>
        /// 生成基础接口和容器抽象类
        /// </summary>
        public static void GenerateInterface(string outputPath, string ns)
        {
            var sb = new StringBuilder();
            sb.Append("/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");
            sb.Append("\tpublic interface ICfg\n\t{\n\t}\n\n");
            sb.Append("\tinternal interface IBinarySerialize\n\t{\n");
            sb.Append("\t\tvoid Serialize(BinaryWriter writer);\n");
            sb.Append("\t\tvoid Deserialize(BinaryReader reader);\n\t}\n\n");
            sb.Append("\tinternal interface ICfgContainer : IBinarySerialize\n\t{\n\t}\n");
            sb.Append("}\n");
            WriteFile(Path.Combine(outputPath, "IBinarySerialize.cs"), sb.ToString());

            GenerateContainerBase(outputPath, ns);
        }

        private static void GenerateContainerBase(string outputPath, string ns)
        {
            var sb = new StringBuilder();
            sb.Append("/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\nusing System.Linq;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");
            sb.Append("\tinternal enum CfgKeyType { Int, Str }\n\n");
            sb.Append("\tpublic abstract class CfgContainerBase<T> : ICfgContainer where T : class, ICfg\n");
            sb.Append("\t{\n");
            sb.Append("\t\tprivate CfgKeyType _keyType;\n");
            sb.Append("\t\tprivate Dictionary<int, T> _intKeyMap;\n");
            sb.Append("\t\tprivate Dictionary<string, T> _strKeyMap;\n\n");
            sb.Append("\t\tprotected void InitIntKey(int capacity)\n\t\t{\n");
            sb.Append("\t\t\t_keyType = CfgKeyType.Int;\n");
            sb.Append("\t\t\t_intKeyMap = new Dictionary<int, T>(capacity);\n\t\t}\n\n");
            sb.Append("\t\tprotected void InitStrKey(int capacity)\n\t\t{\n");
            sb.Append("\t\t\t_keyType = CfgKeyType.Str;\n");
            sb.Append("\t\t\t_strKeyMap = new Dictionary<string, T>(capacity);\n\t\t}\n\n");
            sb.Append("\t\tprotected void AddInt(int key, T value) => _intKeyMap.Add(key, value);\n");
            sb.Append("\t\tprotected void AddStr(string key, T value) => _strKeyMap.Add(key, value);\n");
            sb.Append("\t\tprotected int GetCount() => _keyType == CfgKeyType.Int ? _intKeyMap.Count : _strKeyMap.Count;\n\n");
            sb.Append("\t\tabstract internal void Deserialize(BinaryReader reader);\n");
            sb.Append("\t\tabstract internal void Serialize(BinaryWriter writer);\n\n");
            sb.Append("\t\tpublic T Find(int id)\n\t\t{\n");
            sb.Append("\t\t\tif (_keyType == CfgKeyType.Int)\n");
            sb.Append("\t\t\t\treturn _intKeyMap.TryGetValue(id, out var val) ? val : null;\n");
            sb.Append("\t\t\treturn null;\n\t\t}\n\n");
            sb.Append("\t\tpublic T Find(string id)\n\t\t{\n");
            sb.Append("\t\t\tif (_keyType == CfgKeyType.Str)\n");
            sb.Append("\t\t\t\treturn _strKeyMap.TryGetValue(id, out var val) ? val : null;\n");
            sb.Append("\t\t\treturn null;\n\t\t}\n\n");
            sb.Append("\t\tpublic T Find(Func<T, bool> func) => GetValues().FirstOrDefault(func);\n\n");
            sb.Append("\t\tpublic List<T> FindAll() => GetValues().ToList();\n\n");
            sb.Append("\t\tpublic List<T> FindAll(Func<T, bool> func) => GetValues().Where(func).ToList();\n\n");
            sb.Append("\t\tpublic IEnumerable<T> GetValues()\n\t\t{\n");
            sb.Append("\t\t\tif (_keyType == CfgKeyType.Int) return _intKeyMap.Values;\n");
            sb.Append("\t\t\treturn _strKeyMap.Values;\n\t\t}\n\n");
            sb.Append("\t\tpublic int Count => GetCount();\n");
            sb.Append("\t}\n}\n");
            WriteFile(Path.Combine(outputPath, "CfgContainerBase.cs"), sb.ToString());
        }

        /// <summary>
        /// 生成配置的C#数据类和容器类
        /// </summary>
        public static void GenerateCfgCs(string typeName, string outputPath, List<(string, string)> head, string ns)
        {
            string keyType = TypeHelper.GetKeyType(head);
            var sb = new StringBuilder();
            sb.Append($"/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n * {typeName}\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");

            // 数据类
            sb.Append($"\tpublic partial class {typeName} : ICfg\n");
            sb.Append("\t{\n");
            foreach (var item in head)
                sb.Append($"\t\tpublic {TypeHelper.GetCsType(item.Item2)} {item.Item1} {{ get; private set; }}\n");

            // Deserialize
            sb.Append("\n\t\tinternal void Deserialize(BinaryReader reader)\n\t\t{\n");
            foreach (var item in head)
            {
                string fieldType = item.Item2;
                string fieldName = item.Item1;

                if (TypeHelper.TryParseDictType(fieldType, out string dk, out string dv))
                {
                    sb.Append($"\t\t\t{fieldName} = new Dictionary<{dk}, {dv}>();\n");
                    sb.Append($"\t\t\tint _{fieldName}_count = reader.ReadInt32();\n");
                    sb.Append($"\t\t\tfor (int _i = 0; _i < _{fieldName}_count; _i++) {fieldName}[reader.{TypeHelper.GetReadMethod(dk)}()] = reader.{TypeHelper.GetReadMethod(dv)}();\n");
                }
                else
                {
                    switch (fieldType)
                    {
                        case "int": sb.Append($"\t\t\t{fieldName} = reader.ReadInt32();\n"); break;
                        case "bool": sb.Append($"\t\t\t{fieldName} = reader.ReadBoolean();\n"); break;
                        case "string": sb.Append($"\t\t\t{fieldName} = reader.ReadString();\n"); break;
                        case "int[]":
                            sb.Append($"\t\t\t{fieldName} = new int[reader.ReadInt32()];\n");
                            sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) {fieldName}[_i] = reader.ReadInt32();\n");
                            break;
                        case "string[]":
                            sb.Append($"\t\t\t{fieldName} = new string[reader.ReadInt32()];\n");
                            sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) {fieldName}[_i] = reader.ReadString();\n");
                            break;
                        case "bool[]":
                            sb.Append($"\t\t\t{fieldName} = new bool[reader.ReadInt32()];\n");
                            sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) {fieldName}[_i] = reader.ReadBoolean();\n");
                            break;
                        default: sb.Append($"\t\t\t{fieldName} = reader.ReadString();\n"); break;
                    }
                }
            }
            sb.Append("\t\t}\n\n");

            // Serialize
            sb.Append("\t\tinternal void Serialize(BinaryWriter writer)\n\t\t{\n");
            foreach (var item in head)
            {
                string fieldType = item.Item2;
                string fieldName = item.Item1;
                if (TypeHelper.TryParseDictType(fieldType, out _, out _))
                {
                    sb.Append($"\t\t\twriter.Write({fieldName}.Count);\n");
                    sb.Append($"\t\t\tforeach (var _kv in {fieldName}) {{ writer.Write(_kv.Key); writer.Write(_kv.Value); }}\n");
                }
                else if (fieldType == "int[]" || fieldType == "string[]" || fieldType == "bool[]")
                {
                    sb.Append($"\t\t\twriter.Write({fieldName}.Length);\n");
                    sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) writer.Write({fieldName}[_i]);\n");
                }
                else
                {
                    sb.Append($"\t\t\twriter.Write({fieldName});\n");
                }
            }
            sb.Append("\t\t}\n\t}\n\n");

            // 容器类
            sb.Append($"\tpublic partial class {typeName}Container : CfgContainerBase<{typeName}>\n");
            sb.Append("\t{\n");
            sb.Append("\t\tinternal override void Deserialize(BinaryReader reader)\n\t\t{\n");
            sb.Append("\t\t\tint count = reader.ReadInt32();\n");
            if (keyType == "int")
            {
                sb.Append("\t\t\tInitIntKey(count);\n");
                sb.Append("\t\t\tfor (int i = 0; i < count; i++)\n\t\t\t{\n");
                sb.Append($"\t\t\t\tvar item = new {typeName}();\n");
                sb.Append("\t\t\t\titem.Deserialize(reader);\n");
                sb.Append("\t\t\t\tAddInt(item.Id, item);\n\t\t\t}\n");
            }
            else
            {
                sb.Append("\t\t\tInitStrKey(count);\n");
                sb.Append("\t\t\tfor (int i = 0; i < count; i++)\n\t\t\t{\n");
                sb.Append($"\t\t\t\tvar item = new {typeName}();\n");
                sb.Append("\t\t\t\titem.Deserialize(reader);\n");
                sb.Append("\t\t\t\tAddStr(item.Id, item);\n\t\t\t}\n");
            }
            sb.Append("\t\t}\n\n");
            sb.Append("\t\tinternal override void Serialize(BinaryWriter writer)\n\t\t{\n");
            sb.Append("\t\t\twriter.Write(GetCount());\n");
            sb.Append("\t\t\tforeach (var item in GetValues()) item.Serialize(writer);\n");
            sb.Append("\t\t}\n\t}\n}\n");

            WriteFile(Path.Combine(outputPath, $"{typeName}.cs"), sb.ToString());
        }

        /// <summary>
        /// 生成GameCfgData总管理类
        /// </summary>
        public static void GenerateCfgMap(string outputPath, List<(string typeName, string keyType)> allTypes, string ns)
        {
            string name = "GameCfgData";
            var sb = new StringBuilder();
            sb.Append($"/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n * {name}\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");
            sb.Append($"\tpublic partial class {name}\n");
            sb.Append("\t{\n");
            sb.Append("\t\tprivate Dictionary<Type, ICfgContainer> _cfgDatas;\n\n");
            sb.Append("\t\tpublic void Deserialize(BinaryReader reader)\n\t\t{\n");
            sb.Append("\t\t\t_cfgDatas = new Dictionary<Type, ICfgContainer>();\n\n");

            foreach (var (typeName, _) in allTypes)
            {
                sb.Append($"\t\t\tvar _{typeName}Container = new {typeName}Container();\n");
                sb.Append($"\t\t\t_{typeName}Container.Deserialize(reader);\n");
                sb.Append($"\t\t\t_cfgDatas.Add(typeof({typeName}), _{typeName}Container);\n\n");
            }

            sb.Append("\t\t}\n\n");
            sb.Append("\t\tpublic void Serialize(BinaryWriter writer)\n\t\t{\n");
            sb.Append("\t\t\tforeach (var item in _cfgDatas.Values) item.Serialize(writer);\n");
            sb.Append("\t\t}\n\n");
            sb.Append("\t\tpublic CfgContainerBase<T> GetContainer<T>() where T : class, ICfg\n\t\t{\n");
            sb.Append("\t\t\tif (_cfgDatas.TryGetValue(typeof(T), out var container))\n");
            sb.Append("\t\t\t\treturn container as CfgContainerBase<T>;\n");
            sb.Append("\t\t\treturn null;\n\t\t}\n");
            sb.Append("\t}\n}\n");

            WriteFile(Path.Combine(outputPath, $"{name}.cs"), sb.ToString());
        }

        private static void WriteFile(string filePath, string content)
        {
            File.WriteAllText(filePath, content, Encoding.UTF8);
        }
    }
}
