using System.Text;

namespace ExcelTool
{
    /// <summary>
    /// C#代码生成器
    /// </summary>
    internal static class CodeGenerator
    {
        /// <summary>
        /// 生成基础接口和容器抽象类
        /// </summary>
        public static void GenerateInterface(string outputPath, string ns)
        {
            var sb = new StringBuilder();
            sb.Append("/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");
            sb.Append("\tpublic interface ICfg\n\t{\n\t}\n\n");
            sb.Append("\tinternal interface IBinarySerialize\n\t{\n");
            sb.Append("\t\tvoid Serialize(BinaryWriter writer);\n");
            sb.Append("\t\tvoid Deserialize(BinaryReader reader);\n\t}\n\n");
            sb.Append("\tinternal interface ICfgContainer : IBinarySerialize\n\t{\n\t}\n");
            sb.Append("}\n");
            WriteFile(Path.Combine(outputPath, "IBinarySerialize.cs"), sb.ToString());

            GenerateContainerBase(outputPath, ns);
            GenerateDecryptScript(outputPath, ns);
        }

        private static void GenerateContainerBase(string outputPath, string ns)
        {
            var sb = new StringBuilder();
            sb.Append("/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\nusing System.Linq;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");
            sb.Append("\tinternal enum CfgKeyType { Int, Str }\n\n");
            sb.Append("\tpublic abstract class CfgContainerBase<T> : ICfgContainer where T : class, ICfg\n");
            sb.Append("\t{\n");
            sb.Append("\t\tprivate CfgKeyType _keyType;\n");
            sb.Append("\t\tprivate Dictionary<int, T> _intKeyMap;\n");
            sb.Append("\t\tprivate Dictionary<string, T> _strKeyMap;\n\n");
            sb.Append("\t\tprotected void InitIntKey(int capacity)\n\t\t{\n");
            sb.Append("\t\t\t_keyType = CfgKeyType.Int;\n");
            sb.Append("\t\t\t_intKeyMap = new Dictionary<int, T>(capacity);\n\t\t}\n\n");
            sb.Append("\t\tprotected void InitStrKey(int capacity)\n\t\t{\n");
            sb.Append("\t\t\t_keyType = CfgKeyType.Str;\n");
            sb.Append("\t\t\t_strKeyMap = new Dictionary<string, T>(capacity);\n\t\t}\n\n");
            sb.Append("\t\tprotected void AddInt(int key, T value) => _intKeyMap.Add(key, value);\n");
            sb.Append("\t\tprotected void AddStr(string key, T value) => _strKeyMap.Add(key, value);\n");
            sb.Append("\t\tprotected int GetCount() => _keyType == CfgKeyType.Int ? _intKeyMap.Count : _strKeyMap.Count;\n\n");
            sb.Append("\t\tvoid IBinarySerialize.Deserialize(BinaryReader reader)\n\t\t{\n");
            sb.Append("\t\t\tDeserialize(reader);\n");
            sb.Append("\t\t}\n");
            sb.Append("\t\tvoid IBinarySerialize.Serialize(BinaryWriter writer)\n\t\t{\n");
            sb.Append("\t\t\tSerialize(writer);\n");
            sb.Append("\t\t}\n");
            sb.Append("\t\tabstract protected void Deserialize(BinaryReader reader);\n");
            sb.Append("\t\tabstract protected void Serialize(BinaryWriter writer);\n\n");
            sb.Append("\t\tpublic T Find(int id)\n\t\t{\n");
            sb.Append("\t\t\tif (_keyType == CfgKeyType.Int)\n");
            sb.Append("\t\t\t\treturn _intKeyMap.TryGetValue(id, out var val) ? val : null;\n");
            sb.Append("\t\t\treturn null;\n\t\t}\n\n");
            sb.Append("\t\tpublic T Find(string id)\n\t\t{\n");
            sb.Append("\t\t\tif (_keyType == CfgKeyType.Str)\n");
            sb.Append("\t\t\t\treturn _strKeyMap.TryGetValue(id, out var val) ? val : null;\n");
            sb.Append("\t\t\treturn null;\n\t\t}\n\n");
            sb.Append("\t\tpublic T Find(Func<T, bool> func) => GetValues().FirstOrDefault(func);\n\n");
            sb.Append("\t\tpublic T[] FindAll() => GetValues().ToArray();\n\n");
            sb.Append("\t\tpublic T[] FindAll(Func<T, bool> func) => GetValues().Where(func).ToArray();\n\n");
            sb.Append("\t\tinternal IEnumerable<T> GetValues()\n\t\t{\n");
            sb.Append("\t\t\tif (_keyType == CfgKeyType.Int) return _intKeyMap.Values;\n");
            sb.Append("\t\t\treturn _strKeyMap.Values;\n\t\t}\n\n");
            sb.Append("\t\tpublic int Count => GetCount();\n");
            sb.Append("\t}\n}\n");
            WriteFile(Path.Combine(outputPath, "CfgContainerBase.cs"), sb.ToString());
        }

        /// <summary>
        /// 生成配置的C#数据类和容器类
        /// </summary>
        public static void GenerateCfgCs(string typeName, string outputPath, List<(string, string)> head, string ns)
        {
            string keyType = TypeHelper.GetKeyType(head);
            var sb = new StringBuilder();
            sb.Append($"/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n * {typeName}\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");

            // 数据类
            sb.Append($"\tpublic partial class {typeName} : ICfg\n");
            sb.Append("\t{\n");
            foreach (var item in head)
                sb.Append($"\t\tpublic {TypeHelper.GetCsType(item.Item2)} {item.Item1} {{ get; private set; }}\n");

            // Deserialize
            sb.Append("\n\t\tinternal void Deserialize(BinaryReader reader)\n\t\t{\n");
            foreach (var item in head)
            {
                string fieldType = item.Item2;
                string fieldName = item.Item1;

                if (TypeHelper.TryParseDictType(fieldType, out string dk, out string dv))
                {
                    sb.Append($"\t\t\t{fieldName} = new Dictionary<{dk}, {dv}>();\n");
                    sb.Append($"\t\t\tint _{fieldName}_count = reader.ReadInt32();\n");
                    sb.Append($"\t\t\tfor (int _i = 0; _i < _{fieldName}_count; _i++) {fieldName}[reader.{TypeHelper.GetReadMethod(dk)}()] = reader.{TypeHelper.GetReadMethod(dv)}();\n");
                }
                else
                {
                    switch (fieldType)
                    {
                        case "int": sb.Append($"\t\t\t{fieldName} = reader.ReadInt32();\n"); break;
                        case "bool": sb.Append($"\t\t\t{fieldName} = reader.ReadBoolean();\n"); break;
                        case "string": sb.Append($"\t\t\t{fieldName} = reader.ReadString();\n"); break;
                        case "int[]":
                            sb.Append($"\t\t\t{fieldName} = new int[reader.ReadInt32()];\n");
                            sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) {fieldName}[_i] = reader.ReadInt32();\n");
                            break;
                        case "string[]":
                            sb.Append($"\t\t\t{fieldName} = new string[reader.ReadInt32()];\n");
                            sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) {fieldName}[_i] = reader.ReadString();\n");
                            break;
                        case "bool[]":
                            sb.Append($"\t\t\t{fieldName} = new bool[reader.ReadInt32()];\n");
                            sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) {fieldName}[_i] = reader.ReadBoolean();\n");
                            break;
                        default: sb.Append($"\t\t\t{fieldName} = reader.ReadString();\n"); break;
                    }
                }
            }
            sb.Append("\t\t}\n\n");

            // Serialize
            sb.Append("\t\tinternal void Serialize(BinaryWriter writer)\n\t\t{\n");
            foreach (var item in head)
            {
                string fieldType = item.Item2;
                string fieldName = item.Item1;
                if (TypeHelper.TryParseDictType(fieldType, out _, out _))
                {
                    sb.Append($"\t\t\twriter.Write({fieldName}.Count);\n");
                    sb.Append($"\t\t\tforeach (var _kv in {fieldName}) {{ writer.Write(_kv.Key); writer.Write(_kv.Value); }}\n");
                }
                else if (fieldType == "int[]" || fieldType == "string[]" || fieldType == "bool[]")
                {
                    sb.Append($"\t\t\twriter.Write({fieldName}.Length);\n");
                    sb.Append($"\t\t\tfor (int _i = 0; _i < {fieldName}.Length; _i++) writer.Write({fieldName}[_i]);\n");
                }
                else
                {
                    sb.Append($"\t\t\twriter.Write({fieldName});\n");
                }
            }
            sb.Append("\t\t}\n\t}\n\n");

            // 容器类
            sb.Append($"\tpublic partial class {typeName}Container : CfgContainerBase<{typeName}>\n");
            sb.Append("\t{\n");
            sb.Append("\t\tprotected override void Deserialize(BinaryReader reader)\n\t\t{\n");
            sb.Append("\t\t\tint count = reader.ReadInt32();\n");
            if (keyType == "int")
            {
                sb.Append("\t\t\tInitIntKey(count);\n");
                sb.Append("\t\t\tfor (int i = 0; i < count; i++)\n\t\t\t{\n");
                sb.Append($"\t\t\t\tvar item = new {typeName}();\n");
                sb.Append("\t\t\t\titem.Deserialize(reader);\n");
                sb.Append("\t\t\t\tAddInt(item.Id, item);\n\t\t\t}\n");
            }
            else
            {
                sb.Append("\t\t\tInitStrKey(count);\n");
                sb.Append("\t\t\tfor (int i = 0; i < count; i++)\n\t\t\t{\n");
                sb.Append($"\t\t\t\tvar item = new {typeName}();\n");
                sb.Append("\t\t\t\titem.Deserialize(reader);\n");
                sb.Append("\t\t\t\tAddStr(item.Id, item);\n\t\t\t}\n");
            }
            sb.Append("\t\t}\n\n");
            sb.Append("\t\tprotected override void Serialize(BinaryWriter writer)\n\t\t{\n");
            sb.Append("\t\t\twriter.Write(GetCount());\n");
            sb.Append("\t\t\tforeach (var item in GetValues()) item.Serialize(writer);\n");
            sb.Append("\t\t}\n\t}\n}\n");

            WriteFile(Path.Combine(outputPath, $"{typeName}.cs"), sb.ToString());
        }

        /// <summary>
        /// 生成GameCfgData总管理类
        /// </summary>
        public static void GenerateCfgMap(string outputPath, List<(string typeName, string keyType)> allTypes, string ns)
        {
            string name = "GameCfgData";
            var sb = new StringBuilder();
            sb.Append($"/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n * {name}\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Collections.Generic;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");
            sb.Append($"\tpublic partial class {name}\n");
            sb.Append("\t{\n");
            sb.Append("\t\tprivate Dictionary<Type, ICfgContainer> _cfgDatas;\n\n");
            sb.Append("\t\tpublic void Deserialize(BinaryReader reader)\n\t\t{\n");
            sb.Append("\t\t\t_cfgDatas = new Dictionary<Type, ICfgContainer>();\n\n");

            foreach (var (typeName, _) in allTypes)
            {
                sb.Append($"\t\t\tICfgContainer _{typeName}Container = new {typeName}Container();\n");
                sb.Append($"\t\t\t_{typeName}Container.Deserialize(reader);\n");
                sb.Append($"\t\t\t_cfgDatas.Add(typeof({typeName}), _{typeName}Container);\n\n");
            }

            sb.Append("\t\t}\n\n");
            sb.Append("\t\tpublic void Serialize(BinaryWriter writer)\n\t\t{\n");
            sb.Append("\t\t\tforeach (var item in _cfgDatas.Values) item.Serialize(writer);\n");
            sb.Append("\t\t}\n\n");
            sb.Append("\t\tpublic CfgContainerBase<T> GetContainer<T>() where T : class, ICfg\n\t\t{\n");
            sb.Append("\t\t\tif (_cfgDatas.TryGetValue(typeof(T), out var container))\n");
            sb.Append("\t\t\t\treturn container as CfgContainerBase<T>;\n");
            sb.Append("\t\t\treturn null;\n\t\t}\n");
            sb.Append("\t}\n}\n");

            WriteFile(Path.Combine(outputPath, $"{name}.cs"), sb.ToString());
        }

        /// <summary>
        /// 生成解密脚本
        /// </summary>
        private static void GenerateDecryptScript(string outputPath, string ns)
        {
            var sb = new StringBuilder();
            sb.Append("/*\n * auto generated by tools(注意:此文件由程序生成，请勿手动修改)\n * 配置文件解密工具\n */\n");
            sb.Append("using System;\nusing System.IO;\nusing System.Security.Cryptography;\nusing System.Text;\n\n");
            sb.Append($"namespace {ns}\n");
            sb.Append("{\n");
            sb.Append("\t/// <summary>\n");
            sb.Append("\t/// 加密算法类型\n");
            sb.Append("\t/// </summary>\n");
            sb.Append("\tpublic enum EncryptionAlgorithm\n");
            sb.Append("\t{\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// 无加密\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tNone = 0,\n");
            sb.Append("\t\t\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// 异或加密\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tXOR = 1,\n");
            sb.Append("\t\t\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// AES加密\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tAES = 2,\n");
            sb.Append("\t\t\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// 简单位移加密\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tShift = 3\n");
            sb.Append("\t}\n\n");
            sb.Append("\t/// <summary>\n");
            sb.Append("\t/// 配置文件解密器\n");
            sb.Append("\t/// </summary>\n");
            sb.Append("\tpublic static class CfgDecryptor\n");
            sb.Append("\t{\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// 解密数据\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\t/// <param name=\"data\">加密后的字节数据</param>\n");
            sb.Append("\t\t/// <param name=\"key\">密钥字符串</param>\n");
            sb.Append("\t\t/// <param name=\"algorithm\">加密算法</param>\n");
            sb.Append("\t\t/// <returns>解密后的字节数据</returns>\n");
            sb.Append("\t\tpublic static byte[] Decrypt(byte[] data, string key, EncryptionAlgorithm algorithm = EncryptionAlgorithm.XOR)\n");
            sb.Append("\t\t{\n");
            sb.Append("\t\t\tif (string.IsNullOrEmpty(key) || algorithm == EncryptionAlgorithm.None)\n");
            sb.Append("\t\t\t\treturn data;\n\n");
            sb.Append("\t\t\treturn algorithm switch\n");
            sb.Append("\t\t\t{\n");
            sb.Append("\t\t\t\tEncryptionAlgorithm.XOR => XorTransform(data, key),\n");
            sb.Append("\t\t\t\tEncryptionAlgorithm.AES => AesTransform(data, key, false),\n");
            sb.Append("\t\t\t\tEncryptionAlgorithm.Shift => ShiftTransform(data, key, false),\n");
            sb.Append("\t\t\t\t_ => XorTransform(data, key)\n");
            sb.Append("\t\t\t};\n");
            sb.Append("\t\t}\n\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// 异或变换\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tprivate static byte[] XorTransform(byte[] data, string key)\n");
            sb.Append("\t\t{\n");
            sb.Append("\t\t\tbyte[] keyBytes = Encoding.UTF8.GetBytes(key);\n");
            sb.Append("\t\t\tbyte[] result = new byte[data.Length];\n");
            sb.Append("\t\t\tfor (int i = 0; i < data.Length; i++)\n");
            sb.Append("\t\t\t\tresult[i] = (byte)(data[i] ^ keyBytes[i % keyBytes.Length]);\n");
            sb.Append("\t\t\treturn result;\n");
            sb.Append("\t\t}\n\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// AES变换\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tprivate static byte[] AesTransform(byte[] data, string key, bool encrypt)\n");
            sb.Append("\t\t{\n");
            sb.Append("\t\t\tusing var aes = Aes.Create();\n");
            sb.Append("\t\t\taes.Key = DeriveKey(key, 32); // 256-bit key\n");
            sb.Append("\t\t\taes.IV = DeriveKey(key + \"IV\", 16); // 128-bit IV\n");
            sb.Append("\t\t\t\n");
            sb.Append("\t\t\tusing var transform = encrypt ? aes.CreateEncryptor() : aes.CreateDecryptor();\n");
            sb.Append("\t\t\treturn transform.TransformFinalBlock(data, 0, data.Length);\n");
            sb.Append("\t\t}\n\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// 位移变换\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tprivate static byte[] ShiftTransform(byte[] data, string key, bool encrypt)\n");
            sb.Append("\t\t{\n");
            sb.Append("\t\t\tbyte[] keyBytes = Encoding.UTF8.GetBytes(key);\n");
            sb.Append("\t\t\tbyte[] result = new byte[data.Length];\n");
            sb.Append("\t\t\t\n");
            sb.Append("\t\t\tfor (int i = 0; i < data.Length; i++)\n");
            sb.Append("\t\t\t{\n");
            sb.Append("\t\t\t\tbyte keyByte = keyBytes[i % keyBytes.Length];\n");
            sb.Append("\t\t\t\tint shift = keyByte % 7 + 1; // 1-7位位移\n");
            sb.Append("\t\t\t\t\n");
            sb.Append("\t\t\t\tif (encrypt)\n");
            sb.Append("\t\t\t\t\tresult[i] = (byte)((data[i] << shift) | (data[i] >> (8 - shift)));\n");
            sb.Append("\t\t\t\telse\n");
            sb.Append("\t\t\t\t\tresult[i] = (byte)((data[i] >> shift) | (data[i] << (8 - shift)));\n");
            sb.Append("\t\t\t}\n");
            sb.Append("\t\t\t\n");
            sb.Append("\t\t\treturn result;\n");
            sb.Append("\t\t}\n\n");
            sb.Append("\t\t/// <summary>\n");
            sb.Append("\t\t/// 从字符串派生密钥\n");
            sb.Append("\t\t/// </summary>\n");
            sb.Append("\t\tprivate static byte[] DeriveKey(string key, int size)\n");
            sb.Append("\t\t{\n");
            sb.Append("\t\t\tusing var sha256 = SHA256.Create();\n");
            sb.Append("\t\t\tbyte[] hash = sha256.ComputeHash(Encoding.UTF8.GetBytes(key));\n");
            sb.Append("\t\t\t\n");
            sb.Append("\t\t\t// 如果需要的长度小于哈希长度，截取；如果大于，扩展\n");
            sb.Append("\t\t\tif (size <= hash.Length)\n");
            sb.Append("\t\t\t\treturn hash[..size];\n");
            sb.Append("\t\t\t\n");
            sb.Append("\t\t\t// 扩展密钥\n");
            sb.Append("\t\t\tbyte[] result = new byte[size];\n");
            sb.Append("\t\t\tint copied = 0;\n");
            sb.Append("\t\t\twhile (copied < size)\n");
            sb.Append("\t\t\t{\n");
            sb.Append("\t\t\t\tint toCopy = Math.Min(hash.Length, size - copied);\n");
            sb.Append("\t\t\t\tArray.Copy(hash, 0, result, copied, toCopy);\n");
            sb.Append("\t\t\t\tcopied += toCopy;\n");
            sb.Append("\t\t\t\t\n");
            sb.Append("\t\t\t\t// 如果需要更多数据，重新哈希\n");
            sb.Append("\t\t\t\tif (copied < size)\n");
            sb.Append("\t\t\t\t\thash = sha256.ComputeHash(hash);\n");
            sb.Append("\t\t\t}\n");
            sb.Append("\t\t\t\n");
            sb.Append("\t\t\treturn result;\n");
            sb.Append("\t\t}\n");
            sb.Append("\t}\n");
            sb.Append("}\n");

            WriteFile(Path.Combine(outputPath, "CfgDecryptor.cs"), sb.ToString());
        }

        private static void WriteFile(string filePath, string content)
        {
            File.WriteAllText(filePath, content, Encoding.UTF8);
        }
    }
}
