/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 * GameCfgData
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	public partial class GameCfgData
	{
		private Dictionary<Type, ICfgContainer> _cfgDatas;

		public void Deserialize(BinaryReader reader)
		{
			_cfgDatas = new Dictionary<Type, ICfgContainer>();

			ICfgContainer _LanguageCfgContainer = new LanguageCfgContainer();
			_LanguageCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(LanguageCfg), _LanguageCfgContainer);

			ICfgContainer _ItemCfgContainer = new ItemCfgContainer();
			_ItemCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(ItemCfg), _ItemCfgContainer);

			ICfgContainer _SkillCfgContainer = new SkillCfgContainer();
			_SkillCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(SkillCfg), _SkillCfgContainer);

			ICfgContainer _TipsCfgContainer = new TipsCfgContainer();
			_TipsCfgContainer.Deserialize(reader);
			_cfgDatas.Add(typeof(TipsCfg), _TipsCfgContainer);

		}

		public void Serialize(BinaryWriter writer)
		{
			foreach (var item in _cfgDatas.Values) item.Serialize(writer);
		}

		public CfgContainerBase<T> GetContainer<T>() where T : class, ICfg
		{
			if (_cfgDatas.TryGetValue(typeof(T), out var container))
				return container as CfgContainerBase<T>;
			return null;
		}
	}
}
