/*
 * auto generated by tools(注意:此文件由程序生成，请勿手动修改)
 */
using System;
using System.IO;
using System.Collections.Generic;

namespace Game.Cfg
{
	public interface ICfg
	{
	}

	internal interface IBinarySerialize
	{
		void Serialize(BinaryWriter writer);
		void Deserialize(BinaryReader reader);
	}

	internal interface ICfgContainer : IBinarySerialize
	{
	}
}
